name: build-project
run-name: Building the project
on:
  push:
    branches: [ main ]
jobs:
  build-project:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - run: cd ${{ github.workspace }}
      - run: ls -la
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./cmd/...
      # - name: Test with the Go CLI
      #   run: go test
      - uses: actions/upload-artifact@v2
        with: 
          name: go-example
          path: ./go-example