name: pre-release
run-name: Building the project for Pre Release

on:
  push:
    branches: [main]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.x"
      - run: cd ${{ github.workspace }}
      - run: ls -la
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -o ./output/app -v ./cmd/...
      # - name: Test with the Go CLI
      #   run: go test
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: app
      #     path: ./output/app
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          title: "Development Build"
          files: |
            LICENSE
            ./output/app
